apiVersion: v1
kind: Pod
metadata:
 labels:
   purpose: affinity
 name: pod-1
spec:
 containers:
 # docker run -d --name nginx nginx
 - name: nginx
   image: nginx
---   
apiVersion: v1
kind: Pod
metadata:
 name: pod-2
spec:
 affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - affinity
 containers:
 # docker run -d --name nginx nginx
 - name: nginx
   image: nginx